In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
import numpy as np

np.random.seed(0)

# Load the data
data = pd.read_csv('training_data.csv', delimiter=';')

# Replace commas in numeric columns and convert them to floats
data = data.replace(',', '.', regex=True).apply(pd.to_numeric, errors='ignore')
data.drop('Perform', axis=1, inplace=True)

/var/folders/rg/2t9xl9h93wjdygv93x4f6s4r0000gn/T/ipykernel_81551/2896621310.py:14: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  data = data.replace(',', '.', regex=True).apply(pd.to_numeric, errors='ignore')


In [17]:
data

Group        I1        I2        I3        I4        I5        I6  \
0       G9  0.136495 -0.028429 -0.037772 -0.232459 -0.016222 -0.187506   
1       G5 -0.714522 -0.042137 -0.052968 -0.796862 -0.018394  0.070102   
2      G10  0.104791 -0.038188 -0.053191  0.620233  0.148587  0.489875   
3       G2 -0.532847 -0.006582 -0.023377  1.306702 -0.068909  0.048024   
4       G3 -0.200815 -0.016334 -0.036754 -0.886675  0.484495 -1.148744   
...    ...       ...       ...       ...       ...       ...       ...   
7995    G1 -0.946477 -0.039767 -0.051916       NaN -9.099326  1.470616   
7996    G7 -0.521183 -0.038272 -0.047929 -0.820632 -0.179414 -0.774646   
7997    G2  0.323233 -0.031075 -0.045713 -0.105448 -0.103823  0.153551   
7998    G4  1.084416 -0.028497 -0.047528 -0.180118 -0.634162  0.143589   
7999    G2  0.373261 -0.030294 -0.042319  0.675851 -0.099477 -0.113594   

            I7        I8        I9  ...      dI50      dI51      dI52  \
0    -0.322545 -0.043743  0.125389  ...  0.077110  0.102563  0.188481   
1    -0.076321 -0.063864 -1.045521  ...  0.006128 -0.016375  0.020727   
2     0.319274 -0.060246  0.053174  ...       NaN  0.272937  0.774169   
3    -0.119481 -0.021057 -1.012916  ...       NaN  0.004938  0.018494   
4     0.152517 -0.043580 -0.935537  ... -0.095963 -0.014812 -0.324584   
...        ...       ...       ...  ...       ...       ...       ...   
7995  1.470374 -0.045827 -1.323460  ...       NaN       NaN       NaN   
7996  0.413706 -0.051830 -0.378937  ... -0.105101 -0.168750  0.120571   
7997 -0.052157 -0.056057 -0.163512  ...  0.167119  0.245000  0.079662   
7998 -0.033258 -0.058396  0.088713  ... -0.280183 -0.041688 -0.238481   
7999 -0.347344 -0.053667  0.004552  ... -0.065587 -0.053937 -0.073351   

          dI53      dI54      dI55      dI56      dI57      dI58  Class  
0    -0.016027 -0.135451 -0.189667  0.250967  0.022171 -0.004265     -1  
1    -0.006525 -0.018790 -0.098543  0.317744 -0.180502 -0.009215      1  
2    -0.007144  0.123954  0.000000 -0.110103  0.186669 -0.030720      1  
3    -0.003350 -0.029214  0.045747 -0.076884 -0.037859 -0.012046     -1  
4    -0.019002 -0.379323 -0.046024  0.282145  0.011008  0.010496      1  
...        ...       ...       ...       ...       ...       ...    ...  
7995 -0.015913  0.019281 -0.000427 -0.642472 -4.266003  0.009687      1  
7996 -0.010506 -0.100286 -0.198928  0.053720 -0.001450 -0.001877      1  
7997 -0.009150 -0.191322 -0.083576  0.024407  0.299832 -0.011129      1  
7998  0.006060 -0.016044       NaN  0.209235 -0.165349  0.012005     -1  
7999 -0.000804 -0.118711 -0.106933 -0.034372  0.017757  0.005796      0  

[8000 rows x 118 columns]

In [18]:
# Handle categorical variables - encoding the 'Group' column
le = LabelEncoder()
data['Group'] = le.fit_transform(data['Group'])

# Replace NaN values with 0
# data = data.fillna(0)
# Fill NaN values with the mean of each column
data = data.apply(lambda x: x.fillna(x.mean()), axis=0)

# Assume 'Class' is the target variable
X = data.drop('Class', axis=1)  # Features
y = data['Class']  # Target variable

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [19]:
# Initialize the Decision Tree Classifier
dt_classifier = RandomForestClassifier(n_estimators=100 ,random_state=42)

# Train the classifier
dt_classifier.fit(X_train, y_train)

# Predict on the test set
y_pred = dt_classifier.predict(X_test)

# Evaluate the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.470625
Classification Report:
              precision    recall  f1-score   support

          -1       0.44      0.40      0.42       622
           0       0.20      0.01      0.03       216
           1       0.49      0.66      0.56       762

    accuracy                           0.47      1600
   macro avg       0.38      0.36      0.34      1600
weighted avg       0.43      0.47      0.43      1600

Confusion Matrix:
[[249   6 367]
 [ 68   3 145]
 [255   6 501]]


# Testing